p2/root/urls.py
"""p2 Root URLs"""
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from django.views.generic import RedirectView

from p2.ui.views.errors import ServerErrorView

admin.site.index_title = 'p2 Admin'
admin.site.site_title = 'p2'
admin.site.login = RedirectView.as_view(
    pattern_name='p2_ui:index', permanent=True, query_string=True)

# pylint: disable=invalid-name
handler500 = ServerErrorView.as_view()

# S3 URLs get routed via middleware
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='p2_ui:index')),
    path('_/admin/', admin.site.urls),
    path('_/api/', include('p2.api.urls', namespace='p2_api')),
    path('_/ui/', include('p2.ui.urls', namespace='p2_ui')),
    path('_/oidc/', include('mozilla_django_oidc.urls')),
    path('_/auth/password/', views.PasswordChangeView.as_view(), name='auth_password'),
    path('_/auth/login/', views.LoginView.as_view(), name='auth_login'),
    path('_/auth/logout/', views.LogoutView.as_view(), name='auth_logout'),
    path('', include('p2.s3.urls', namespace='p2_s3')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('_/debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

p2/s3/urls.py
"""p2 S3 URLs"""
from django.urls import path, register_converter
from django.urls.converters import StringConverter

from p2.s3.views import buckets, objects


class S3BucketConverter(StringConverter):
    """Match S3 bucket regex"""

    regex = r'([a-zA-Z0-9\.\-\_]+)'


class EverythingConverter(StringConverter):
    """Match Everything. Just used for debugging"""

    regex = '.*'


register_converter(S3BucketConverter, 's3')
register_converter(EverythingConverter, 'everything')

app_name = 'p2_s3'

# These patterns are always available and don't require an AWS Header
urlpatterns = [
    path('<s3:bucket>/', buckets.BucketView.as_view(), name='bucket'),
    path('<s3:bucket>/<everything:path>', objects.ObjectView.as_view(), name='bucket-object'),
]

p2/ui/urls.py
"""UI URLS"""
from django.urls import path

from p2.ui.views import general
from p2.ui.views.api import key
from p2.ui.views.core import blob, component, storage, volume
from p2.ui.views.iam import users
from p2.ui.views.serve import rule

app_name = 'p2_ui'
urlpatterns = [
    # General
    path('', general.IndexView.as_view(), name='index'),
    path('search/', general.SearchView.as_view(), name='search'),
    # Core - Volumes
    path('core/volume/',
         volume.VolumeListView.as_view(), name='core-volume-list'),
    path('core/volume/create/',
         volume.VolumeCreateView.as_view(), name='core-volume-create'),
    path('core/volume/<uuid:pk>/',
         volume.VolumeDetailView.as_view(), name='core-volume-detail'),
    path('core/volume/<uuid:pk>/update/',
         volume.VolumeUpdateView.as_view(), name='core-volume-update'),
    path('core/volume/<uuid:pk>/delete/',
         volume.VolumeDeleteView.as_view(), name='core-volume-delete'),
    path('core/volume/<uuid:pk>/blobs/',
         blob.FileBrowserView.as_view(), name='core-blob-list'),
    # Core - Blobs
    # Blob creation disabled for now
    # path('core/blob/create/',
    #      blob.BlobCreateView.as_view(), name='core-blob-create'),
    path('core/blob/<uuid:pk>/',
         blob.BlobDetailView.as_view(), name='core-blob-detail'),
    path('core/blob/<uuid:pk>/update/',
         blob.BlobUpdateView.as_view(), name='core-blob-update'),
    path('core/blob/<uuid:pk>/delete/',
         blob.BlobDeleteView.as_view(), name='core-blob-delete'),
    path('core/blob/<uuid:pk>/download/',
         blob.BlobDownloadView.as_view(), name='core-blob-download'),
    # Core - Components
    path('core/volume/<uuid:pk>/component/create/',
         component.ComponentCreateView.as_view(), name='core-component-create'),
    path('core/component/<uuid:pk>/update/',
         component.ComponentUpdateView.as_view(), name='core-component-update'),
    path('core/component/<uuid:pk>/delete/',
         component.ComponentDeleteView.as_view(), name='core-component-delete'),
    # Core - Storages
    path('core/storage/',
         storage.StorageListView.as_view(), name='core-storage-list'),
    path('core/storage/create/',
         storage.StorageCreateView.as_view(), name='core-storage-create'),
    path('core/storage/<uuid:pk>/',
         storage.StorageDetailView.as_view(), name='core-storage-detail'),
    path('core/storage/<uuid:pk>/update/',
         storage.StorageUpdateView.as_view(), name='core-storage-update'),
    path('core/storage/<uuid:pk>/delete/',
         storage.StorageDeleteView.as_view(), name='core-storage-delete'),
    # API - Keys
    path('iam/users/',
         users.UserListView.as_view(), name='iam-users-list'),
    path('iam/users/create/',
         users.UserCreateView.as_view(), name='iam-users-create'),
    path('iam/users/<int:pk>/update/',
         users.UserUpdateView.as_view(), name='iam-users-update'),
    path('iam/users/<int:pk>/delete/',
         users.UserDeleteView.as_view(), name='iam-users-delete'),
    # API - Keys
    path('api/access-key/',
         key.APIKeyListView.as_view(), name='api-key-list'),
    path('api/access-key/create/',
         key.APIKeyCreateView.as_view(), name='api-key-create'),
    path('api/access-key/<int:pk>/update/',
         key.APIKeyUpdateView.as_view(), name='api-key-update'),
    path('api/access-key/<int:pk>/delete/',
         key.APIKeyDeleteView.as_view(), name='api-key-delete'),
    # Serve - Rules
    path('serve/rule/',
         rule.ServeRuleListView.as_view(), name='serve-rule-list'),
    path('serve/rule/create/',
         rule.ServeRuleCreateView.as_view(), name='serve-rule-create'),
    path('serve/rule/<uuid:pk>/debug/',
         rule.ServeRuleDebugView.as_view(), name='serve-rule-debug'),
    path('serve/rule/<uuid:pk>/update/',
         rule.ServeRuleUpdateView.as_view(), name='serve-rule-update'),
    path('serve/rule/<uuid:pk>/delete/',
         rule.ServeRuleDeleteView.as_view(), name='serve-rule-delete'),
]

p2/ui/views/errors.py
"""p2 error views"""
import sys
import traceback

from django.http.response import (HttpResponseBadRequest,
                                  HttpResponseForbidden, HttpResponseNotFound,
                                  HttpResponseServerError)
from django.template.response import TemplateResponse
from django.views.generic import TemplateView
from sentry_sdk import last_event_id


class BadRequestTemplateResponse(TemplateResponse, HttpResponseBadRequest):
    """Combine Template response with Http Code 400"""


class ForbiddenTemplateResponse(TemplateResponse, HttpResponseForbidden):
    """Combine Template response with Http Code 403"""


class NotFoundTemplateResponse(TemplateResponse, HttpResponseNotFound):
    """Combine Template response with Http Code 404"""


class ServerErrorTemplateResponse(TemplateResponse, HttpResponseServerError):
    """Combine Template response with Http Code 500"""


class ServerErrorView(TemplateView):
    """Show server error message and sentry feedback integration"""

    response_class = ServerErrorTemplateResponse
    template_name = 'errors/500.html'

    def dispatch(self, *args, **kwargs):
        """Little wrapper so django accepts this function"""
        type_, _error, trace = sys.exc_info()
        self.extra_context = {
            'exception': str(type_),
            'error': traceback.format_tb(trace),
            'hide_navbar': True,
            'sentry_event_id': last_event_id()
        }
        return super().dispatch(*args, **kwargs)

p2/ui/views/general.py
"""p2 UI Index view"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.views.generic import ListView
from guardian.mixins import PermissionListMixin
from guardian.shortcuts import get_objects_for_user

from p2.core.models import Blob, Volume
from p2.ui.constants import CACHE_KEY_BLOB_COUNT


class IndexView(LoginRequiredMixin, PermissionListMixin, ListView):
    """Show overview of volumes"""

    model = Volume
    permission_required = 'p2_core.view_volume'
    template_name = 'general/index.html'
    ordering = 'name'
    paginate_by = 9

    def get_queryset(self, *args, **kwrags):
        return super().get_queryset(*args, **kwrags).select_related('storage')

    def get_blob_count(self):
        """Get cached Blob Count"""
        if not cache.get(CACHE_KEY_BLOB_COUNT, None):
            count = len(Blob.objects.all())
            cache.set(CACHE_KEY_BLOB_COUNT, count, 30)
        return cache.get(CACHE_KEY_BLOB_COUNT)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['count'] = self.get_blob_count()
        return data

class SearchView(LoginRequiredMixin, ListView):
    """Search Blobs by their key"""

    model = Blob
    ordering = 'path'
    template_name = 'search/results.html'

    def get_queryset(self):
        return get_objects_for_user(self.request.user, 'p2_core.view_blob').filter(
            path__icontains=self.request.GET.get('q', '')).order_by(self.ordering)

p2/ui/templates/p2_core/blob_detail.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load static %}

{% load p2_ui %}

{% block head %}
{{ block.super }}
{{ form.media }}
<script src="{% static 'codemirror/codemirror.js' %}"></script>
<link rel="stylesheet" href="{% static 'codemirror/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'codemirror/theme/monokai.css' %}">
<script src="{% static 'codemirror/mode/javascript.js' %}"></script>
{% endblock %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12 py-md-3">
      {% include 'blocks/messages.html' %}
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'p2_ui:core-blob-list' pk=object.volume.pk %}?prefix=/">{{ object.volume.name|truncatechars:160 }}</a></li>
          {% for crumb in breadcrumbs %}
            <li class="breadcrumb-item"><a href="{% url 'p2_ui:core-blob-list' pk=object.volume.pk %}?prefix={{ crumb.prefix }}">{{ crumb.title|truncatechars:160 }}</a></li>
          {% endfor %}
          <li class="breadcrumb-item active" aria-current="page">{{ object.filename|truncatechars:160 }}</li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      {% with object|get_attribute:"p2.core.constants.ATTR_BLOB_IS_TEXT" as is_text %}
      {% with object|get_attribute:"p2.core.constants.ATTR_BLOB_MIME" as mime %}
      {% if is_text %}
        {% include 'p2_core/blob_detail_text.html' with object=object only %}
      {% elif mime|startswith:'image/' %}
        {% include 'p2_core/blob_detail_image.html' with object=object only %}
      {% else %}
        {% include 'p2_core/blob_detail_fallback.html' with object=object only %}
      {% endif %}
      {% endwith %}
      {% endwith %}
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{% trans 'Metadata' %}</h5>
        </div>
        <table class="table table-bordered table-hover table-sm mb-0">
          <tbody>
            <tr>
              <th>{% trans 'Path' %}</th>
              <td>{{ object.path }}</td>
            </tr>
            <tr>
              <th>{% trans 'Volume' %}</th>
              <td>
                <a href="{% url 'p2_ui:core-volume-detail' pk=object.volume.pk %}">{{ object.volume }}</a>
              </td>
            </tr>
            <tr>
              <th>{% trans 'Attributes' %}</th>
              <td>
                <table class="table table-striped table-bordered table-hover table-sm">
                  <tbody>
                    {% for key, value in object.attributes.items|dictsort:"0.lower" %}
                    <tr>
                      <th>{{ key }}</th>
                      <td>{{ value }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <th>{% trans 'Tags' %}</th>
              <td>
                <table class="table table-striped table-bordered table-hover table-sm">
                  <tbody>
                    {% for key, value in object.tags.items|dictsort:"0.lower" %}
                    <tr>
                      <th>{{ key }}</th>
                      <td>{{ value }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <hr>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{% trans 'Actions' %}</h5>
          <a href="{% url 'p2_ui:core-blob-download' pk=object.pk %}" class="btn btn-primary">{% trans 'Download' %}</a>
          <a href="{% url 'p2_ui:core-blob-update' pk=object.pk %}" class="btn btn-primary">{% trans 'Edit' %}</a>
          <a href="{% url 'p2_ui:core-blob-delete' pk=object.pk %}" class="btn btn-danger">{% trans 'Delete' %}</a>
        </div>
      </div>
      <hr>
      <div class="card"><div class="card-body">
        <h5 class="card-title">{% trans 'Permissions' %}</h5>
        <table class="table table-striped table-bordered table-hover table-sm mb-0">
          {% regroup permissions by user as permission_list %}
          <thead>
            <tr>
              <th>{% trans 'User' %}</th>
              {% for perm in model_perms %}
              <th>{{ perm.name }}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for user, user_perms in users_perms.items %}
            <tr>
              <td>{{ user }}</td>
              {% for perm in model_perms %}
              <td>
                {% if perm.codename in user_perms %}
                <i class="fa fa-check text-success" aria-hidden="true"></i>
                {% else %}
                <i class="fa fa-times text-danger" aria-hidden="true"></i>
                {% endif %}
              </td>
              {% endfor %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

p2/ui/templates/p2_core/blob_detail_fallback.html
{% load i18n %}
{% load p2_ui %}

<style>
  iframe.blob-payload {
    height: calc(100vh - 152px - 35px - 35px);
    width: 100%;
  }
</style>
<div class="blob-detail-container">
  <h3>{% trans "We're not sure how to preview this file." %}</h3><br>
  <button class="btn btn-primary show-iframe">{% trans 'Try anyway' %}</button>
</div>

{% block scripts %}
<script>
  $('button.show-iframe').on('click', (e) => {
    // debugger;
    $('button.show-iframe').parent().empty();
    $('<iframe>', {
      src: '{{ object|blob_url }}',
      class: "blob-payload",
    }).appendTo('.blob-detail-container');
  });
</script>
{% endblock %}

p2/ui/templates/p2_core/blob_detail_image.html
{% load p2_ui %}

<style>
  img.blob-payload {
    max-width: 100%;
  }
</style>
<img class="blob-payload" src="{{ object|blob_url }}" alt="">

p2/ui/templates/p2_core/blob_detail_text.html
{% load i18n %}
{% load static %}

{% load p2_ui %}

<button class="btn btn-primary btn-sm">{% trans 'Save' %}</button>
<hr>
<style>
  .CodeMirror {
    height: auto;
  }
</style>
<textarea name="payload">{{ object|blob_string }}</textarea>
{% with object|get_attribute:"p2.core.constants.ATTR_BLOB_MIME" as mime %}
<script src="{% static 'codemirror/addon/mode/loadmode.js' %}"></script>
<script src="{% static 'codemirror/mode/meta.js' %}"></script>
<script>
  CodeMirror.modeURL = "{% static 'codemirror/mode/' %}%N/%N.js";
  let payload = document.getElementsByName('payload');
  if (payload.length > 0) {
    // Try to detect file-type from mime, fall back to extension
    let info = CodeMirror.findModeByMIME("{{ mime }}");
    if (info.mode === "null") {
      const ext = /.+\.([^.]+)$/.exec("{{ object.path }}");
      info = CodeMirror.findModeByExtension(ext[1]);
    }
    let myCodeMirror = CodeMirror.fromTextArea(payload[0], {
      mode: 'javascript',
      theme: 'monokai',
      lineNumbers: true,
      viewportMargin: Infinity,
    });
    myCodeMirror.setOption("mode", "{{ mime }}");
    CodeMirror.autoLoadMode(myCodeMirror, info.mode);
    console.log(`Detected ${info.mode} filetype`)
  }
</script>
{% endwith %}

p2/ui/templates/p2_core/blob_list.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load p2_ui %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12 py-md-3">
      {% include 'blocks/messages.html' %}
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'p2_ui:core-volume-detail' pk=volume.pk %}?prefix=/">{{ volume.name }}</a></li>
          {% for crumb in breadcrumbs %}
            {% if not forloop.last %}
              <li class="breadcrumb-item"><a href="{% url 'p2_ui:core-blob-list' pk=volume.pk %}?prefix={{ crumb.full }}">{{ crumb.part|truncatechars:160 }}</a></li>
            {% endif %}
            {% if forloop.last %}
              <li class="breadcrumb-item active" aria-current="page">{{ crumb.part|truncatechars:160 }}</li>
            {% endif %}
          {% endfor %}
        </ol>
      </nav>
      <form action="{% url 'p2_api:volume-upload' pk=volume.pk %}?prefix={{ request.GET.prefix }}" class="dz" method="POST">
        {% csrf_token %}
        <table class="table table-striped table-bordered table-hover table-sm">
          <thead class="thead-dark">
            <tr>
              <th>{% trans 'Path' %}</th>
              <th>{% trans 'Size' %}</th>
              <th>{% trans 'Actions' %}</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>
                {% if 'blob.p2.io/is_folder' in object.attributes %}
                <a href="?prefix={{ object.path }}">
                  <i class="fa fa-folder" aria-hidden="true"></i>
                  {{ object.filename|truncatechars:160 }}
                </a>
                {% else %}
                <a href="{% url 'p2_ui:core-blob-detail' pk=object.pk %}">
                  <i class="fa fa-file" aria-hidden="true"></i>
                  {{ object.filename|truncatechars:160 }}
                </a>
                {% endif %}
              </td>
              <td>{{ object|get_attribute:"p2.core.constants.ATTR_BLOB_SIZE_BYTES"|filesizeformat }}</td>
              <td>
                <a class="btn btn-sm btn-primary" href="{% url 'p2_ui:core-blob-download' pk=object.pk %}">
                  <i class="fa fa-download text-light" aria-hidden="true"></i>
                </a>
                <a class="btn btn-sm btn-primary" href="{% url 'p2_ui:core-blob-update' pk=object.pk %}">
                  <i class="fa fa-pencil text-light" aria-hidden="true"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'p2_ui:core-blob-delete' pk=object.pk %}">
                  <i class="fa fa-trash text-light" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </form>
    </div>
  </div>
</div>
{% include 'blocks/pagination.html' %}
{% endblock %}

p2/ui/templates/p2_core/storage_detail.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load static %}

{% load p2_ui %}

{% block head %}
{{ block.super }}
{{ form.media }}
<script src="{% static 'codemirror/codemirror.js' %}"></script>
<link rel="stylesheet" href="{% static 'codemirror/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'codemirror/theme/monokai.css' %}">
<script src="{% static 'codemirror/mode/javascript.js' %}"></script>
{% endblock %}

{% block content %}
<h2>
  {% blocktrans with storage=object.name %}Storage {{ storage }}{% endblocktrans %}
</h2>
<div class="row">
  <table class="table table-striped table-bordered table-hover table-sm">
    <tbody>
      <tr>
        <td>{% trans 'Controller' %}</td>
        <td>{{ object.controller_path }}</td>
      </tr>
      <tr>
        <td>{% trans 'Total Blobs' %}</td>
        <td>{{ total_blobs }}</td>
      </tr>
      <tr>
        <td>{% trans 'Total space used' %}</td>
        <td>{{ total_space|filesizeformat }}</td>
      </tr>
      <tr>
        <td>{% trans 'Tags' %}</td>
        <td>
          <textarea name="tags">{{ object.tags|json }}</textarea>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<script>
  let tags = document.getElementsByName('tags');
  if (tags.length > 0) {
    let myCodeMirror = CodeMirror.fromTextArea(tags[0], {
      mode: 'javascript',
      theme: 'monokai',
      lineNumbers: true,
      viewportMargin: Infinity,
    });
  }
</script>
{% endblock %}

p2/ui/templates/p2_core/storage_list.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
<h2>
  {% trans 'Storages' %}
  <a class="btn btn-success" href="{% url 'p2_ui:core-storage-create' %}">
    <i class="fa fa-plus text-light" aria-hidden="true"></i>
  </a>
</h2>
<table class="table table-striped table-bordered table-hover table-sm">
  <thead class="thead-dark">
    <tr>
      <th>{% trans 'Name' %}</th>
      <th>{% trans 'Controller' %}</th>
      <th>{% trans 'Actions' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>
          <a href="{% url 'p2_ui:core-storage-detail' pk=object.pk %}">
            {{ object.name }}
          </a>
      </td>
      <td>{{ object.controller_path }}</td>
      <td>
        <a class="btn btn-primary" href="{% url 'p2_ui:core-storage-update' pk=object.pk %}">
          <i class="fa fa-pencil text-light" aria-hidden="true"></i>
        </a>
        <a class="btn btn-danger" href="{% url 'p2_ui:core-storage-delete' pk=object.pk %}">
          <i class="fa fa-trash text-light" aria-hidden="true"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if paginator.num_pages > 1 %}
{% include 'blocks/pagination.html' %}
{% endif %}
{% endblock %}

p2/ui/templates/p2_core/volume_detail.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
<h2>
  {% blocktrans with volume=object.name %}Volume {{ volume }}{% endblocktrans %}
</h2>
<div class="row">
  <div class="col-md-4 py-md-1">
    <div class="card">
      <div class="card-body text-white bg-primary">
        <h5 class="card-title">{% trans 'Blob Browser' %}</h5>
        <h6 class="card-subtitle mb-2">
          {% blocktrans %}
          Browse blobs saved in this Volume.
          {% endblocktrans %}
        </h6>
        <a href="{% url 'p2_ui:core-blob-list' pk=volume.pk %}" class="card-link btn btn-outline btn-sm btn-primary">{% trans 'Browse' %}</a>
      </div>
    </div>
  </div>
  <div class="col-md-4 py-md-1">
    <div class="card">
      <div class="card-body text-white bg-primary">
        <h5 class="card-title">{% trans 'Re-Index' %}</h5>
        <h6 class="card-subtitle mb-2">
          {% blocktrans %}
          Re-Index all blobs in this Volume. Use this after you've changed a component which updates new blobs to apply changes to existing blobs.
          {% endblocktrans %}
        </h6>
        <button data-api-url="{% url 'p2_api:volume-re-index' pk=volume.pk %}" class="card-link btn btn-outline btn-sm btn-primary">{% trans 'Re-Index' %}</button>
      </div>
    </div>
  </div>
  {% for component in components %}
  <div class="col-md-4 py-md-1">
    {% include component.controller.template_name with component=component %}
  </div>
  {% endfor %}
</div>
{% endblock %}

p2/ui/templates/p2_core/volume_list.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
<h2>
  {% trans 'Volumes' %}
  <a class="btn btn-success" href="{% url 'p2_ui:core-volume-create' %}">
    <i class="fa fa-plus text-light" aria-hidden="true"></i>
  </a>
</h2>
<table class="table table-striped table-bordered table-hover table-sm">
  <thead class="thead-dark">
    <tr>
      <th>{% trans 'Name' %}</th>
      <th>{% trans 'Storage' %}</th>
      <th>{% trans 'Actions' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>
        <a href="{% url 'p2_ui:core-volume-detail' pk=object.pk %}">
          {{ object.name }}
        </a>
      </td>
      <td>{{ object.storage.name }}</td>
      <td>
        <a class="btn btn-primary" href="{% url 'p2_ui:core-volume-update' pk=object.pk %}">
          <i class="fa fa-pencil text-light" aria-hidden="true"></i>
        </a>
        <a class="btn btn-danger" href="{% url 'p2_ui:core-volume-delete' pk=object.pk %}">
          <i class="fa fa-trash text-light" aria-hidden="true"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if paginator.num_pages > 1 %}
{% include 'blocks/pagination.html' %}
{% endif %}
{% endblock %}